import { Injectable } from '@nestjs/common';
import { Customer } from './interfaces/customer.interface';
import { CreateCustomerDto } from './dto/create-customer.dto';

@Injectable()
export class CustomersService {
    // user defined array to store customers, in real application this will be replaced by database
    private customers: Customer[] = [];

    // return all customers
    // where Customer[]{} is the return type of the function, it means that this function will return an array of Customer objects
    getAllCustomers(): Customer[] {
        return this.customers;
    }

             // parameter       :   type of parameter  : return type of function
    addCustomer(createCustomerDto: CreateCustomerDto) : Customer {
        const newCustomer: Customer = {
            id: Date.now(), // using timestamp as a unique id for simplicity, in real application this will be generated by database
            ...createCustomerDto // spread operator to copy properties from createCustomerDto to newCustomer
        }
        this.customers.push(newCustomer); // add new customer to the array
        return newCustomer; // return the newly created customer
    }
}
